name: NicholasVitale
favicon: null
layout_spectrum: 0.7947652502916753
typography_spectrum: 0.5657622076105326
title: 'Nicholas Vitale  '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f7e86'
    - '#523e86'
    - '#854d00'
    - '#296203'
    - '#910006'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.68118169112131
  rhythmicContrast: 0.4931534130591899
purpose: []
