name: NicholasVitale
favicon: null
layout_spectrum: 0.7947652502916753
typography_spectrum: 0.5657622076105326
title: 'Nicholas Vitale  '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ea8c0'
    - '#4e6d89'
    - '#c9c9c7'
    - '#1d2228'
    - '#38414a'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.68118169112131
  rhythmicContrast: 0.4931534130591899
purpose: []
